pipelines:
  - name: build_bi_yahav
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "8.0.0"
      environmentVariables:
        readOnly:
          NEXT_VERSION: 0.0.0
          NEXT_DEVELOPMENT_VERSION: 0.0.x-SNAPSHOT
          NEXT_GRADLE_VERSION: 0.0.0
          NEXT_GRADLE_DEVELOPMENT_VERSION: 0.0.x-SNAPSHOT

    steps:
      - name: Release
        type: Bash
        configuration:
          inputResources:
            - name: biReleaseYahavGit
          integrations:
            - name: jfrog
            - name: yahav_github
        execution:
          onStart:
            - restore_cache_files gradle_cache $res_biReleaseYahavGit_resourcePath/.gradle
          onExecute:
            - cd $res_biReleaseYahavGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_CLI_BUILD_NAME=build-info
            - export JFROG_CLI_BUILD_NUMBER=$run_number

            # Configure git
            - git checkout master
            - git remote set-url origin https://$int_yahav_github_generic_token@yahav_github.com/jfrog/build-info.git

            # Make sure versions provided
            - echo "Checking variables"
            - test -n "$NEXT_VERSION" -a "$NEXT_VERSION" != "0.0.0"
            - test -n "$NEXT_GRADLE_VERSION" -a "$NEXT_GRADLE_VERSION" != "0.0.0"
            - test -n "$NEXT_DEVELOPMENT_VERSION" -a "$NEXT_DEVELOPMENT_VERSION" != "0.0.0"
            - test -n "$NEXT_GRADLE_DEVELOPMENT_VERSION" -a "$NEXT_GRADLE_DEVELOPMENT_VERSION" != "0.0.0"

            # Configure JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog
            - ./jfrog c add jfrog --artifactory-url $int_jfrog_rt_url --user=$int_jfrog_rt_user --password=$int_jfrog_rt_password
            - ./jfrog rt gradlec --use-wrapper --uses-plugin
              --server-id-resolve jfrog --repo-resolve remote-repos
              --server-id-deploy jfrog --repo-deploy oss-release-local

            # Run install and publish
            - >
              ORG_GRADLE_PROJECT_signingKey=$int_mvn_central_signingKey
              ORG_GRADLE_PROJECT_signingPassword=$int_mvn_central_signingPassword
              ./jfrog rt gradle clean aP -x test
            - ./jfrog rt bag
            - ./jfrog rt bp

          onComplete:
            # Save .m2 cache
            - add_cache_files $res_biReleaseYahavGit_resourcePath/.gradle gradle_cache
